version: "3"
services:
  hugoserver:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    command: server --bind 0.0.0.0 --navigateToChanged --templateMetrics --buildDrafts
    ports:
      - 80:1313
